### ISSUE TITLE
NoMethodError (undefined method `encode' for JsonWebToken:Module)

### ISSUE THREAD

**Issue by minosahu31** [jwt/ruby-jwt#329]
Hi All,

I am facing a problem with JWT gem file after I upgrade my rails version from 4.2 to 5.0.

Can anybody please help me.

I am using **Rails - 5.0.7.2**
                  **Ruby - 2.5.3**
                   **JwT - 2.2.1**

> **require 'jwt'**

**payload = { data: 'test' }**

token = JWT.encode payload, nil, 'none'

Traceback (most recent call last):
        8: from bin/rails:11:in `<main>'
        7: from bin/rails:11:in `require'
        6: from /home/sahu/.rvm/gems/ruby-2.5.3/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        5: from /home/sahu/.rvm/gems/ruby-2.5.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        4: from /home/sahu/.rvm/gems/ruby-2.5.3/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:78:in `console'
        3: from /home/sahu/.rvm/gems/ruby-2.5.3/gems/railties-5.0.7.2/lib/rails/commands/console_helper.rb:9:in `start'
        2: from /home/sahu/.rvm/gems/ruby-2.5.3/gems/railties-5.0.7.2/lib/rails/commands/console.rb:65:in `start'
        1: from (irb):3
NoMethodError (undefined method `encode' for 

> JsonWebToken:Module)

And also getting warnings - 

**/home/sahu/.rvm/gems/ruby-2.5.3/gems/json_web_token-0.3.5/lib/json_web_token.rb:36: warning: already initialized constant JWT**

**/home/sahu/.rvm/gems/ruby-2.5.3/gems/jwt-2.2.1/lib/jwt/base64.rb:5: warning: previous definition of JWT was here**

**Comment by excpt** [comment]
@minosahu31 Thank you for sharing the solution! :)

**Comment by anakinj** [comment]
Think that this also addresses the problem: https://github.com/garyf/json_web_token/pull/6
